#!/bin/bash

JACKETT_VERSION=$(curl --silent "https://api.github.com/repos/Jackett/Jackett/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')

docker push "$IMAGE_NAME" 
docker push "$DOCKER_REPO:$JACKETT_VERSION"