on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 23 * * *"

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get latest jackett version
        shell: bash
        run: >
          echo JACKETT_VERSION=$(curl --silent 'https://api.github.com/repos/Jackett/Jackett/releases/latest' | grep -Po '"tag_name": "\K.*?(?=")') >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          build-args: |
            BUILD_DATE=${{ github.event.repository.updated_at}}
            VCS_REF=${{ github.head_ref }}
            JACKETT_VERSION=${{ env.JACKETT_VERSION }}
          tags: |
            docker.io/guillaumedsde/jackett-distroless:${{ env.JACKETT_VERSION }}
            docker.io/guillaumedsde/jackett-distroless:latest
          platforms: |
            linux/amd64
            linux/arm64
