on:
  push:
  schedule:
    - cron: "0 23 * * *"

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Get latest jackett version
        id: jackett-version-step
        shell: bash
        run: >
          echo JACKETT_VERSION=$(curl --silent 'https://api.github.com/repos/Jackett/Jackett/releases/latest' | grep -Po '"tag_name": "\K.*?(?=")') >> $GITHUB_OUTPUT
      - uses: guillaumedsde/qbittorrent-distroless/.github/workflows/docker.yml@master
        with:
          software-version: ${{ steps.jackett-version-step.outputs.JACKETT_VERSION }}
          platforms: |
            linux/amd64
            linux/arm64