on:
  push:
  schedule:
    - cron: "0 23 * * *"

jobs:
  get-jackett-version:
    runs-on: ubuntu-22.04
    outputs:
      jackett-version: ${{ steps.jackett-version-step.outputs.JACKETT_VERSION }}
    steps:
      - name: Get latest jackett version
        id: jackett-version-step
        shell: bash
        run: >
          echo JACKETT_VERSION=$(curl --silent 'https://api.github.com/repos/Jackett/Jackett/releases/latest' | grep -Po '"tag_name": "\K.*?(?=")') >> $GITHUB_OUTPUT
  docker:
    uses: guillaumedsde/qbittorrent-distroless/.github/workflows/main.yml@master
    with:
      software-version: ${{ needs.get-jackett-version.outputs.jackett-version }}
    secrets: inherit